export const SELECT_ITEM = "SELECT_ITEM";

export const FETCH_API_PENDING = 'FETCH_API_PENDING';
export const FETCH_API_SUCCESS = 'FETCH_API_SUCCESS';
export const FETCH_API_ERROR = 'FETCH_API_ERROR';